# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 03 Jul 2015 06:29:40 +0000
*               @ALL          0
*               @user         8
